# Generated by Django 5.2.3 on 2025-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('emoji', models.TextField(default='😀', verbose_name='emoji')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
