# Generated by Django 5.2.3 on 2025-11-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='역할')),
                ('description', models.TextField(blank=True, verbose_name='소개')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crew_images/', verbose_name='프로필 이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
