# Generated by Django 5.2.3 on 2025-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('link', models.TextField(blank=True, null=True, verbose_name='content1')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
