# Generated by Django 5.2.3 on 2025-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('진행중', '진행중'), ('완료', '완료'), ('중지', '중지')], default='진행중', max_length=10, verbose_name='상태')),
                ('github_repo', models.CharField(blank=True, max_length=200, null=True, verbose_name='GitHub Repo (owner/repo)')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='외부 링크')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
