# Generated by Django 5.1.5 on 2025-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverhowtojoin',
            name='content',
        ),
        migrations.AddField(
            model_name='serverhowtojoin',
            name='content0',
            field=models.TextField(blank=True, null=True, verbose_name='content0'),
        ),
        migrations.AddField(
            model_name='serverhowtojoin',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='content1'),
        ),
        migrations.AddField(
            model_name='serverhowtojoin',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='serverhowtojoin',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
