# Generated by Django 5.1.5 on 2025-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
