# Generated by Django 5.2.3 on 2025-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowndocument',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
            preserve_default=False,
        ),
    ]
