# Generated by Django 5.2.3 on 2025-07-29 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_markdowndocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdowndocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
