# Generated by Django 5.2.3 on 2025-11-28 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='archived', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='important', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='normal', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
