# Generated by Django 5.1.5 on 2025-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='notice',
            name='content0',
            field=models.TextField(blank=True, null=True, verbose_name='content0'),
        ),
        migrations.AddField(
            model_name='notice',
            name='content1',
            field=models.TextField(blank=True, null=True, verbose_name='content1'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='noticeType'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
