# Generated by Django 5.1.5 on 2025-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_options_remove_notice_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='createdAt'),
        ),
    ]
