# Generated by Django 5.2.3 on 2025-06-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('content0', models.TextField(blank=True, null=True, verbose_name='content0')),
                ('content1', models.TextField(blank=True, null=True, verbose_name='content1')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='createdAt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
