# Generated by Django 5.2.3 on 2025-07-18 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_archivednotice_importantnotice_normalnotice_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednotice',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivednotice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='importantnotice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt'),
        ),
        migrations.AlterField(
            model_name='normalnotice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='createdAt'),
        ),
    ]
