# Generated by Django 5.2.3 on 2025-07-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_archivednotice_site_alter_archivednotice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivednotice',
            name='site',
        ),
    ]
