# Generated by Django 5.2.3 on 2025-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_remove_archivednotice_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivednotice',
            name='type',
            field=models.CharField(default='important', max_length=20),
        ),
        migrations.AddField(
            model_name='importantnotice',
            name='type',
            field=models.CharField(default='important', max_length=20),
        ),
        migrations.AddField(
            model_name='normalnotice',
            name='type',
            field=models.CharField(default='important', max_length=20),
        ),
    ]
