# Generated by Django 5.2.3 on 2025-11-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_archivednotice_type_importantnotice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivednotice',
            name='type',
            field=models.CharField(default='archived', max_length=20),
        ),
        migrations.AlterField(
            model_name='normalnotice',
            name='type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
