# Generated by Django 5.2.3 on 2025-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutCrewonessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='name')),
                ('pc_stat', models.TextField(blank=True, null=True, verbose_name='pc_stat')),
                ('game_setting', models.TextField(blank=True, null=True, verbose_name='game_setting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
