# Generated by Django 5.1.5 on 2025-06-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BuildPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('things', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardWorkedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('playtime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedstonePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('things', models.CharField(max_length=255)),
            ],
        ),
    ]
