# Generated by Django 5.1.5 on 2025-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
