# Generated by Django 5.1.5 on 2025-06-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_delete_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardworkedplayer',
            name='playtime_txt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildplayer',
            name='player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildplayer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildplayer',
            name='things',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardworkedplayer',
            name='player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hardworkedplayer',
            name='playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redstoneplayer',
            name='player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redstoneplayer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redstoneplayer',
            name='things',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
